### ISSUE TITLE
HelpScoutDesk Deprecated API code 

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/help-scout#8]
SSLVerify=false outdated API for HelpScoutDesk
=========================================================
Name           |   Deprecated API 
Reporter       |   Elana D.
Submit Date |    12/18/2020
Summary      | debugging logs in HelpScoutDesk for sslverify=false

![image](https://user-images.githubusercontent.com/5271694/102640286-3e05d900-4128-11eb-8747-2ef5b539b616.png)

![image](https://user-images.githubusercontent.com/5271694/102639609-4dd0ed80-4127-11eb-8499-986e41d76d1c.png)

**Comment by neoseeyou** [comment]
Hello,

Any news about this issue? Still not resolved.

Thanks
